version: '3.7'

services:
  backend_django:
    container_name: backend_django
    hostname: backend_django
    restart: always
    build: ./backend/backend_django
    expose:
      - 8080
    env_file:
      - ./backend/backend_django/.env
  backend_nginx:
    container_name: backend_nginx
    hostname: backend_nginx
    restart: always
    build: ./backend/backend_nginx
    ports:
      - 8080:80
    depends_on: 
      - backend_django
  frontend_nginx:
    container_name: frontend_nginx
    hostname: frontend_nginx
    restart: always
    build: ./frontend
    ports:
      - 8081:80